### ISSUE TITLE
Rubotium doesn't find any tests when using Espresso with AndroidJUnitRunner

### ISSUE THREAD

**Issue by stefanhoth** [ssmiech/rubotium#25]
In our project we are using [Espresso](https://code.google.com/p/android-test-kit/wiki/EspressoSetupInstructions) to create UI tests. Since Espresso 2.0 Google supplies a new test runner for projects to use called `android.support.test.runner.AndroidJUnitRunner`.

When running these tests from gradle via `./gradlew clean connectedAndroidTests` 1 test is executed per device.

But calling rubotium via 
`rubotium -t app-test.apk -a  aop,apk -r android.support.test.runner.AndroidJUnitRunner`

I'm getting a lot of output but lastly resulting in calls like
```
EXECUTING_COMMAND: adb -s 43223541314348585753 shell am instrument -w -r -e log true com.example.myapp.test/android.support.test.runner.AndroidJUnitRunner
There are 0 tests to run
```

with result.xml as
```
<testsuites></testsuites>
```

What do I do wrong?

**Comment by ssmiech** [comment]
could you double check please? there seems to be a bug in the line you've pasted `aop,apk` . 

We call it in the following way and all flies: 
`rubotium -a application.apk -t tests.apk -r android.support.test.runner.AndroidJUnitRunner`

**Comment by stefanhoth** [comment]
Sorry, that was just an error by me avoiding leaking any private project info. The line was correct without my redaction.

**Comment by ssmiech** [comment]
That's strange, the Android's shell command `am instrument`

**Comment by ssmiech** [comment]
Which device have you used?

**Comment by ssmiech** [comment]
for some strange reason, with Espresso the logOnly flag does not work 
`adb shell am instrument -w -r -e log true  your.package/android.support.test.runner.AndroidJUnitRunner` results in tests being executed but the `-e log true` should actually prevent that.

**Comment by stefanhoth** [comment]
@ssmiech Yeah, @brigitlyons posted a bug report that is supposedly fixed in the next release of the testrunner.

**Comment by ssmiech** [comment]
https://code.google.com/p/android/issues/detail?id=196066

**Comment by ssmiech** [comment]
@stefanhoth @brigitlyons 
Surprisingly, removing `@RunWith` annotation fixes the issue.

**Comment by ssmiech** [comment]
The issue comes from `AndroidAnnotatedBuilder` which completely ignores the `logOnly` parameter and creates `AndroidJUnit4` runner instead of `NonExecutingJUnit4ClassRunner`
